# Generated by Django 2.2 on 2019-06-28 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affected_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Request')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performed_actions',
            },
        ),
    ]
